[package]
name = "aamva-js"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
strip = true
lto = true

[package.metadata.wasm-pack.profile.release]
wasm-opt = ['-O']

[dependencies]
aamva = { path = "../../" }
serde-wasm-bindgen = "0.6.5"
wasm-bindgen = "0.2.92"
